package com.mooket.social.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.mooket.social.entity.StatBrandProduct;
import java.time.LocalDate;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;

@Mapper
/* loaded from: temp_jar_download.jar:BOOT-INF/classes/com/mooket/social/mapper/StatBrandProductMapper.class */
public interface StatBrandProductMapper extends BaseMapper<StatBrandProduct> {
    @Insert({"<script>INSERT INTO stat_brand_product (stat_date, brand_id, brand_name, product_id, product_name, today_factory_count, today_offer_count, price_min, price_max, avg_price, avg_price_yesterday, price_change, price_change_rate, update_time) VALUES <foreach collection='list' item='item' separator=','>(#{item.statDate}, #{item.brandId}, #{item.brandName}, #{item.productId}, #{item.productName}, #{item.todayFactoryCount}, #{item.todayOfferCount}, #{item.priceMin}, #{item.priceMax}, #{item.avgPrice}, #{item.avgPriceYesterday}, #{item.priceChange}, #{item.priceChangeRate}, #{item.updateTime})</foreach> ON CONFLICT (stat_date, brand_id, product_id) DO UPDATE SET today_factory_count = EXCLUDED.today_factory_count, today_offer_count = EXCLUDED.today_offer_count, price_min = EXCLUDED.price_min, price_max = EXCLUDED.price_max, avg_price = EXCLUDED.avg_price, avg_price_yesterday = EXCLUDED.avg_price_yesterday, price_change = EXCLUDED.price_change, price_change_rate = EXCLUDED.price_change_rate, update_time = EXCLUDED.update_time</script>"})
    void batchUpsert(@Param("list") List<StatBrandProduct> stats);

    @Delete({"DELETE FROM stat_brand_product WHERE stat_date = #{statDate}"})
    void deleteByDate(@Param("statDate") LocalDate statDate);

    @Delete({"DELETE FROM stat_brand_product WHERE stat_date < CURRENT_DATE - INTERVAL '30 day'"})
    int deleteOldRecords();

    @Select({"SELECT\n    MAX(brand_id) AS brand_id,\n    MAX(brand_name) AS brand_name,\n    MAX(product_id) AS product_id,\n    MAX(product_name) AS product_name,\n    SUM(today_factory_count) AS today_factory_count,\n    SUM(today_offer_count) AS today_offer_count,\n    MIN(price_min) AS price_min,\n    MAX(price_max) AS price_max,\n    CASE WHEN SUM(today_offer_count) > 0 THEN ROUND(SUM(avg_price * today_offer_count) / SUM(today_offer_count), 4) ELSE 0 END AS avg_price,\n    CASE WHEN SUM(today_offer_count) > 0 THEN ROUND(SUM(avg_price_yesterday * today_offer_count) / SUM(today_offer_count), 4) ELSE 0 END AS avg_price_yesterday,\n    CASE WHEN SUM(today_offer_count) > 0 THEN ROUND((SUM(avg_price * today_offer_count) / SUM(today_offer_count)) - (SUM(avg_price_yesterday * today_offer_count) / SUM(today_offer_count)), 4) ELSE 0 END AS price_change,\n    CASE WHEN SUM(today_offer_count) > 0 AND SUM(avg_price_yesterday * today_offer_count) / SUM(today_offer_count) != 0 THEN ROUND(((SUM(avg_price * today_offer_count) / SUM(today_offer_count)) - (SUM(avg_price_yesterday * today_offer_count) / SUM(today_offer_count))) / (SUM(avg_price_yesterday * today_offer_count) / SUM(today_offer_count)) * 100, 2) ELSE 0 END AS price_change_rate\nFROM stat_brand_product\nWHERE stat_date = #{statDate}\n  AND today_offer_count >= 10\nGROUP BY REPLACE(brand_name, ' ', ''), REPLACE(product_name, ' ', '')\nORDER BY SUM(today_offer_count) DESC\nLIMIT #{limit}"})
    @Results({@Result(property = "brandId", column = "brand_id"), @Result(property = "brandName", column = "brand_name"), @Result(property = "productId", column = "product_id"), @Result(property = "productName", column = "product_name"), @Result(property = "todayFactoryCount", column = "today_factory_count"), @Result(property = "todayOfferCount", column = "today_offer_count"), @Result(property = "priceMin", column = "price_min"), @Result(property = "priceMax", column = "price_max"), @Result(property = "avgPrice", column = "avg_price"), @Result(property = "avgPriceYesterday", column = "avg_price_yesterday"), @Result(property = "priceChange", column = "price_change"), @Result(property = "priceChangeRate", column = "price_change_rate")})
    List<StatBrandProduct> findHotBrandProducts(@Param("statDate") LocalDate statDate, @Param("limit") int limit);

    @Select({"SELECT brand_id, brand_name, product_id, product_name, today_factory_count, today_offer_count, price_min, price_max, avg_price, avg_price_yesterday, price_change, price_change_rate FROM stat_brand_product WHERE brand_id = #{brandId} AND product_id = #{productId} ORDER BY stat_date DESC LIMIT 1"})
    @Results({@Result(property = "brandId", column = "brand_id"), @Result(property = "brandName", column = "brand_name"), @Result(property = "productId", column = "product_id"), @Result(property = "productName", column = "product_name"), @Result(property = "todayFactoryCount", column = "today_factory_count"), @Result(property = "todayOfferCount", column = "today_offer_count"), @Result(property = "priceMin", column = "price_min"), @Result(property = "priceMax", column = "price_max"), @Result(property = "avgPrice", column = "avg_price"), @Result(property = "avgPriceYesterday", column = "avg_price_yesterday"), @Result(property = "priceChange", column = "price_change"), @Result(property = "priceChangeRate", column = "price_change_rate")})
    StatBrandProduct selectByBrandIdAndProductId(@Param("brandId") Integer brandId, @Param("productId") Integer productId);

    @Select({"SELECT\n    MAX(t.brand_id) AS brand_id,\n    MAX(t.brand_name) AS brand_name,\n    MAX(t.product_id) AS product_id,\n    MAX(t.product_name) AS product_name,\n    SUM(t.today_factory_count) AS today_factory_count,\n    SUM(t.today_offer_count) AS today_offer_count,\n    MIN(t.price_min) AS price_min,\n    MAX(t.price_max) AS price_max,\n    CASE WHEN SUM(t.today_offer_count) > 0 THEN ROUND(SUM(t.avg_price * t.today_offer_count) / SUM(t.today_offer_count), 4) ELSE 0 END AS avg_price,\n    CASE WHEN MAX(y.yesterday_total_count) > 0 THEN ROUND(SUM(y.yesterday_weighted_price) / SUM(y.yesterday_total_count), 4) ELSE 0 END AS avg_price_yesterday,\n    CASE WHEN SUM(t.today_offer_count) > 0 AND MAX(y.yesterday_total_count) > 0 THEN ROUND((SUM(t.avg_price * t.today_offer_count) / SUM(t.today_offer_count)) - (SUM(y.yesterday_weighted_price) / SUM(y.yesterday_total_count)), 4) ELSE 0 END AS price_change,\n    CASE WHEN SUM(t.today_offer_count) > 0 AND MAX(y.yesterday_total_count) > 0 AND (SUM(y.yesterday_weighted_price) / SUM(y.yesterday_total_count)) != 0 THEN ROUND(((SUM(t.avg_price * t.today_offer_count) / SUM(t.today_offer_count)) - (SUM(y.yesterday_weighted_price) / SUM(y.yesterday_total_count))) / (SUM(y.yesterday_weighted_price) / SUM(y.yesterday_total_count)) * 100, 2) ELSE 0 END AS price_change_rate\nFROM stat_brand_product t\nLEFT JOIN (\n    SELECT brand_id, product_id,\n        SUM(avg_price_yesterday * today_offer_count) AS yesterday_weighted_price,\n        SUM(today_offer_count) AS yesterday_total_count\n    FROM stat_brand_product\n    WHERE stat_date = CURRENT_DATE - 1\n      AND REPLACE(brand_name, ' ', '') = REPLACE(#{brandName}, ' ', '')\n      AND REPLACE(product_name, ' ', '') = REPLACE(#{productName}, ' ', '')\n      AND today_offer_count >= 0\n    GROUP BY brand_id, product_id\n) y ON t.brand_id = y.brand_id AND t.product_id = y.product_id\nWHERE t.stat_date = CURRENT_DATE\n  AND REPLACE(t.brand_name, ' ', '') = REPLACE(#{brandName}, ' ', '')\n  AND REPLACE(t.product_name, ' ', '') = REPLACE(#{productName}, ' ', '')\n  AND t.today_offer_count >= 0"})
    @Results({@Result(property = "brandId", column = "brand_id"), @Result(property = "brandName", column = "brand_name"), @Result(property = "productId", column = "product_id"), @Result(property = "productName", column = "product_name"), @Result(property = "todayFactoryCount", column = "today_factory_count"), @Result(property = "todayOfferCount", column = "today_offer_count"), @Result(property = "priceMin", column = "price_min"), @Result(property = "priceMax", column = "price_max"), @Result(property = "avgPrice", column = "avg_price"), @Result(property = "avgPriceYesterday", column = "avg_price_yesterday"), @Result(property = "priceChange", column = "price_change"), @Result(property = "priceChangeRate", column = "price_change_rate")})
    StatBrandProduct selectAggregatedByBrandNameAndProductName(@Param("brandName") String brandName, @Param("productName") String productName);

    @Select({"SELECT\n    stat_date,\n    CASE WHEN SUM(today_offer_count) > 0 THEN ROUND(SUM(avg_price * today_offer_count) / SUM(today_offer_count), 4) ELSE 0 END AS avg_price\nFROM stat_brand_product\nWHERE REPLACE(brand_name, ' ', '') LIKE CONCAT('%', REPLACE(#{brandName}, ' ', ''), '%')\n  AND REPLACE(product_name, ' ', '') = REPLACE(#{productName}, ' ', '')\n  AND today_offer_count >= 0\n  AND stat_date >= CURRENT_DATE - INTERVAL '7 day'\nGROUP BY stat_date\nORDER BY stat_date ASC"})
    @Results({@Result(property = "statDate", column = "stat_date"), @Result(property = "avgPrice", column = "avg_price")})
    List<StatBrandProduct> selectTrendByBrandNameAndProductName(@Param("brandName") String brandName, @Param("productName") String productName);
}